### ISSUE TITLE
More gear

### ISSUE THREAD

**Issue by gwbischof** [IzaKastra/wsdist_beta#3]
Cool program!

Would it make sense to add more gear to it? Like the +2 empy for example.

You can find a complete gear and icon list here: https://www.ffxiah.com/dev/

I could make a few contributions, but I don't know what would be helpful.

**Comment by IzaKastra** [comment]
The gear.py file is excluded from the code compiling. This means you can make any changes you want to the gear.py file and see those changes in the GUI itself after reloading it.

I have no plans to add Empy+2 armor since it clearly loses to Empy+3, but those who wish to test the Empy+2 armor are able to add it themselves to the gear.py file, with basic knowledge of Python3 lists and variables.

If you wanted to add Empy+2, then I recommend copy/pasting the corresponding Empy+3 gear and modifying the stats that way. You'll then need to change the variable name and put the variable in the corresponding list (the variable name for a newly added Empy+2 body would go in the "bodies" list, for example).
